# Generated by Django 5.0 on 2024-01-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='phone_number',
            field=models.IntegerField(max_length=11),
        ),
    ]
