# Generated by Django 5.0 on 2024-01-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Brand',
            new_name='brand',
        ),
    ]
