# Generated by Django 5.0 on 2024-02-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_history_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
